[workspace]
authors = ["intMinsu <minsurcv@gmail.com>"]
channels = ["conda-forge", "pytorch", "aihabitat"]
name = "habitat-extractor"
platforms = ["linux-64"]
version = "0.1.0"
channel-priority = "strict"
preview = ["pixi-build"]

[system-requirements]
linux = "5.4.0"
libc = { family = "glibc", version = "2.31" } # https://github.com/prefix-dev/pixi/issues/3916

[feature.py38.dependencies]
python = "3.8.*"
pip = {channel = "conda-forge", version = "*"}
jupyterlab = {channel = "conda-forge", version = "*"}

[feature.torch112cu116.dependencies]
pytorch =  {channel = "pytorch", version = "==1.12.1"}
torchvision = {channel = "pytorch", version = "==0.13.1"}
torchaudio = {channel = "pytorch", version = "==0.12.1"}
cudatoolkit = {channel = "conda-forge", version = "11.6.*"}
mkl = {channel = "conda-forge", version = "<2024"}

[feature.habitat-22.dependencies]
cmake = {channel = "conda-forge", version = "<4"}
ninja = {channel = "conda-forge", version = "*"}
make = {channel = "conda-forge", version = "*"}
glm = {channel = "conda-forge", version = "*"}
numpy = {channel = "conda-forge", version = "==1.22.4"}
matplotlib = {version = "3.7.*"}
plyfile = "*"
habitat-sim = {channel = "aihabitat", version = "==0.2.2"}
headless = {channel = "aihabitat", version = "*"}
withbullet = {channel = "aihabitat", version = "*"}
trimesh = ">=4.5.3,<5"

[feature.habitat-22.pypi-dependencies]
opencv-python = {version = ">=4.9"}
scikit-image = {version = "*"}
pycolmap = "==3.10.0"
pyceres = {version = "==2.3"}
lightglue = {git = "https://github.com/jytime/LightGlue.git"}

[feature.egl.dependencies]
libegl = "*"            # EGL runtime
libglvnd = "*"          # vendor-neutral GL/EGL/GLX dispatch
mesalib = "*"
mesa-libgl-cos7-x86_64 = "*"
libglib = "*"

# X/GLX stack for non-headless runs (like xvfb-run)
[feature.glx.dependencies]
xorg-libx11 = "*"
xorg-libxext = "*"
xorg-libxrandr = "*"
xorg-libxfixes = "*"
xorg-libxi = "*"
freeglut = "*"
glew = "*"

[feature.pycharm.dependencies]
pixi-pycharm = "*"

[environments]
env = {features = [
    "py38",
    "torch112cu116",
    "habitat-22",
    "egl",
    "glx",
    "pycharm",
]}

[activation.env]
CPATH = "$CONDA_PREFIX/targets/x86_64-linux/include:$CPATH"
CPLUS_INCLUDE_PATH = "$CONDA_PREFIX/targets/x86_64-linux/include:$CPLUS_INCLUDE_PATH"
LIBRARY_PATH = "$CONDA_PREFIX/lib:$LIBRARY_PATH"
LD_LIBRARY_PATH = "$CONDA_PREFIX/lib:$LD_LIBRARY_PATH"
